# -- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    )
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;


# 아래의 코드가 더 좋은 코드인가?
# WHERE절의 튜플(?)을 FOOD_TYPE과 FAVORITES로 설정하는 것이 핵심!
# FOOD_TYPE이 아닌 REST_ID나 REST_NAME을 사용하면 틀린 결과가 도출된다
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
# FROM REST_INFO 
# WHERE (FOOD_TYPE, FAVORITES) IN (
#     SELECT FOOD_TYPE, MAX(FAVORITES) 
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC;