-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER >= 3000
    AND FLAVOR IN (
        SELECT T2.FLAVOR
        FROM ICECREAM_INFO AS T2
        WHERE INGREDIENT_TYPE = "FRUIT_BASED")
ORDER BY TOTAL_ORDER DESC;