-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT(LEFT(TLNO, 3), '-', SUBSTR(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS '전화번호'
FROM USED_GOODS_USER AS T1
    JOIN USED_GOODS_BOARD AS T2
        ON T1.USER_ID = T2.WRITER_ID
GROUP BY T1.USER_ID
HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC;