# 대여기간에 시작일과 종료일을 포함할 때 대여기간은 DATEDIFF()의 결과값에 1을 더한 값이 된다
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7   -- 해당 조건식을 WHERE절로 쓰게 되면 ALIAS를 사용할 수 없어서 코드가 난잡해진다
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;