-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS T1
    JOIN REST_REVIEW AS T2
        ON T1.MEMBER_ID = T2.MEMBER_ID
WHERE T1.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = (
        SELECT MAX(CNT) 
        FROM (SELECT COUNT(*) AS CNT
              FROM REST_REVIEW 
              GROUP BY MEMBER_ID) AS CNTS
        )
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;