# 특정 작가가 동일 장르의 책을 2권 이상 쓴 경우가 존재하므로 저자별 카테고리별 도서의 총 매출액을 도출할 때 주의해야 한다
# SUM(T3.SALES * T1.PRICE) = (각 도서에 대한 판매량 * 가격)의 총합 -> 정답
# SUM(T3.SALES) * T1.PRICE = (모든 도서의 총 판매량) * 특정 도서의 가격 -> 오답
SELECT T1.AUTHOR_ID, T2.AUTHOR_NAME, T1.CATEGORY, SUM(T3.SALES * T1.PRICE) AS TOTAL_SALES
FROM BOOK AS T1
    JOIN AUTHOR AS T2
        ON T1.AUTHOR_ID = T2.AUTHOR_ID
    JOIN BOOK_SALES AS T3
        ON T1.BOOK_ID = T3.BOOK_ID
WHERE T3.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY T1.AUTHOR_ID, T1.CATEGORY
ORDER BY T1.AUTHOR_ID ASC, T1.CATEGORY DESC;