-- 코드를 입력하세요
SELECT T1.AUTHOR_ID, T2.AUTHOR_NAME, T1.CATEGORY, SUM(T3.SALES) * T1.PRICE AS TOTAL_SALES
FROM BOOK AS T1
    JOIN AUTHOR AS T2
        ON T1.AUTHOR_ID = T2.AUTHOR_ID
    JOIN BOOK_SALES AS T3
        ON T1.BOOK_ID = T3.BOOK_ID
WHERE T3.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY T1.AUTHOR_ID, T1.CATEGORY
ORDER BY T1.AUTHOR_ID ASC, T1.CATEGORY DESC;


SELECT T1.AUTHOR_ID, T2.AUTHOR_NAME, T1.CATEGORY, SUM(T3.SALES * T1.PRICE) AS TOTAL_SALES
FROM BOOK AS T1
    JOIN AUTHOR AS T2
        ON T1.AUTHOR_ID = T2.AUTHOR_ID
    JOIN BOOK_SALES AS T3
        ON T1.BOOK_ID = T3.BOOK_ID
WHERE T3.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY T1.AUTHOR_ID, T1.CATEGORY
ORDER BY T1.AUTHOR_ID ASC, T1.CATEGORY DESC;


# SELECT SUM(T2.SALES), T1.PRICE
# FROM BOOK AS T1        
#     JOIN BOOK_SALES AS T2
#         ON T1.BOOK_ID = T2.BOOK_ID
# GROUP BY T1.BOOK_ID
# ORDER BY T1.BOOK_ID
    