-- 코드를 입력하세요
SELECT DISTINCT T1.USER_ID, T1.PRODUCT_ID
FROM ONLINE_SALE AS T1
    JOIN ONLINE_SALE AS T2
        ON T1.USER_ID = T2.USER_ID
            AND T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE T1.ONLINE_SALE_ID != T2.ONLINE_SALE_ID    
ORDER BY USER_ID ASC, PRODUCT_ID DESC;