-- 코드를 입력하세요
SELECT DISTINCT T1.USER_ID, T1.PRODUCT_ID
FROM ONLINE_SALE AS T1
    JOIN ONLINE_SALE AS T2
        ON T1.USER_ID = T2.USER_ID
            AND T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE T1.ONLINE_SALE_ID != T2.ONLINE_SALE_ID    
ORDER BY USER_ID ASC, PRODUCT_ID DESC;


# GROUP BY절에서 두 개 이상의 조건식이 어떤 식으로 동작하는지에 대한 이해가 부족하다!!!
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# GROUP BY USER_ID, PRODUCT_ID
# HAVING COUNT(*) >= 2
# ORDER BY USER_ID ASC, PRODUCT_ID DESC